name: Tests

on:
  push:
    branches: [1.x]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.4', '8.5']

    name: PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: composer test